export const GET_ASSETS = "GET_ASSETS";
export const ADD_ASSETS= "ADD_ASSETS";
export const GET_ASSET_TYPES= "GET_ASSET_TYPE";
export const UPDATE_ASSETS_PAGE_SIZE = "UPDATE_ASSETS_PAGE_SIZE";
export const UPDATE_ASSETS_PAGE= "UPDATE_ASSETS_PAGE";


