export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_CATEGORIES = "ADD_CATEGORIES ";
export const UPDATE_CATEGORIES_PAGE_SIZE = "UPDATE_CATEGORIES_PAGE_SIZE";
export const UPDATE_CATEGORIES_PAGE= "UPDATE_CATEGORIES_PAGE";


