export const GET_COLLECTION = "GET_COLLECTION";
export const ADD_COLLECTION = "ADD_COLLECTION";
export const UPDATE_COLLECTION_PAGE_SIZE = "UPDATE_COLLECTION_PAGE_SIZE";
export const UPDATE_COLLECTION_PAGE= "UPDATE_COLLECTION_PAGE";


